$SERVICE:
  priority: 5 # Lower value means lower priority (Default: 0)
  search:   # Search parameters configuration
  download:
    extract:
    outputs_prefix: /data/
  auth:
    credentials:
      username: $CREODIAS_USERNAME
      password: $CREODIAS_PASSWORD
  storage:
    region_name: null
    endpoint_url_local: $S3_ENDPOINT_URL_LOCAL
    endpoint_url_ext: $S3_ENDPOINT_URL_EXT
    aws_access_key_id: $S3_AWS_ACCESS_KEY_ID
    aws_secret_access_key: $S3_AWS_SECRET_ACCESS_KEY
    config: null
    output_directory: /data/
    bucket: $BUCKET
sentinel-hub:
  instance_id: $SH_INSTANCE_ID
  sh_client_id: $SH_CLIENT_ID
  sh_client_secret: $SH_CLIENT_SECRET
